version: '3.1'

services:

  api:
    image: sairoko12/task-service
    container_name: task-service
    restart: always
    build:
      context: .
      args:
        - APP_PORT=3000
    env_file:
      - .env
    volumes:
      - "./:/usr/src/app"
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    links:
      - mongodb

  mongodb:
    image: mongo:4.1-bionic
    container_name: task-service-db
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodata: